config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /en|pl/ do
    devise_for :users, controllers: { sessions: 'customized_devise/sessions' }

    root 'welcome#index'
    resources :users, except: :show
    resources :product_structures, except: :show
    resources :color_presets, except: :show
    resources :clients, except: :show
    resources :templates, except: :show
    resources :backgrounds, except: :show
    resources :machines, except: :show
    resources :clients, except: :show
    resources :machine_parameters, except: :show
    resources :lacquering_aniloxes, except: :show
    resources :lacquering_names, except: :show
    resources :lacquering_polymers, except: :show
    resources :lacquering_types, except: :show
    resources :lacquering_indices, except: :show
    resources :lamination_glues, except: :show
    resources :lamination_machines, except: :show
    resources :lamination_types, except: :show
    resources :lamination_glue_types, except: :show
    resources :lamination_glue_systems, except: :show
    resources :lamination_indices, except: :show
    resources :lamination_roto_glue_names, except: :show
    resources :lamination_roto_glue_types, except: :show
    resources :lamination_roto_linearities, except: :show
    resources :lamination_roto_presers, except: :show
    resources :lamination_roto_indices, except: :show
    resources :cutting_indices, except: :show
    resources :cutting_machines, except: :show
    resources :roto_linearities, except: :show
    resources :roto_paints, except: :show
    resources :roto_presers, except: :show
    resources :roto_indices, except: :show
    resources :paint_providers, except: :show
    resources :paints, except: :show
    resources :acetate_providers, except: :show
    resources :template_background_providers, except: :show
    resources :template_background_prices, except: :show
    resources :offset_plates, except: :show
    resources :offset_plate_providers, except: :show
    resources :azote_providers, except: :show
    resources :pack_providers, except: :show
    resources :orders do
      member do
        get :actualize_edit
        get :pdf_main
        get :pdf_for_print
        get :pdf_after_print
        get :pdf_lamination_1
        get :pdf_lamination_2
        get :price_edit
        patch :actualize_update
        patch :prepared_update
        patch :rollback_update
        patch :start_print_update
        patch :finish_print_update
        patch :start_cut_update
        patch :finish_cut_update
        patch :give_away_update
        patch :update_order_additional_info
        patch :cant_prepare_materials_update
        patch :start_lamination_first_update
        patch :finish_lamination_first_update
        patch :start_lamination_second_update
        patch :finish_lamination_second_update
        patch :price_update
      end
    end
  end
end

app/controllers/lamination_glue_types_controller.rb
class LaminationGlueTypesController < ApplicationController
  before_action :set_and_authorize_lamination_glue_type, only: [:edit, :update, :destroy]

  # GET /lamination_glue_types
  def index
    authorize LaminationGlueType
    @lamination_glue_types = policy_scope(LaminationGlueType)
    @lamination_glue_types = @lamination_glue_types.order(id: :asc)
    @lamination_glue_types = @lamination_glue_types.page(params[:page]).per(25)
  end

  # GET /lamination_glue_types/new
  def new
    authorize LaminationGlueType
    @lamination_glue_type = LaminationGlueType.new
  end

  # POST /lamination_glue_types
  def create
    authorize LaminationGlueType
    @lamination_glue_type = LaminationGlueType.new(lamination_glue_type_params)
    if @lamination_glue_type.save
      redirect_to lamination_glue_types_url, notice: t('shared.created')
    else
      render :new
    end
  end

  # GET /lamination_glue_types/:id/edit
  def edit
  end

  # PATCH/PUT /lamination_glue_types/:id
  def update
    if @lamination_glue_type.update(lamination_glue_type_params)
      redirect_to edit_lamination_glue_type_url(@lamination_glue_type),
                  notice: t('shared.updated')
    else
      render :edit
    end
  end

  # DELETE /lamination_glue_types/:id
  def destroy
    if @lamination_glue_type.destroy
      redirect_to lamination_glue_types_url, notice: t('shared.destroyed')
    else
      redirect_to lamination_glue_types_url, alert: t('shared.not_destroyed')
    end
  end

  private

  def lamination_glue_type_params
    params.require(:lamination_glue_type).permit(:name, :lamination_type_id)
  end

  def set_and_authorize_lamination_glue_type
    @lamination_glue_type = LaminationGlueType.find(params[:id])
    authorize @lamination_glue_type
  end
end

app/views/lamination_glue_types/_form.html.slim
.box.box-primary
  .box-body
    = simple_form_for @lamination_glue_type, html: { class: 'form-horizontal' } do |f|
      = f.input :name
      = f.input :lamination_type_id, collection: LaminationType.all.map{ |t| [t.name, t.id] }, include_blank: true

      .box-footer
        => link_to t('shared.back'), lamination_glue_types_path, class: 'btn btn-default'
        => f.button :submit, f.object.new_record? ? t('shared.create') : t('shared.save'), class: 'btn btn-primary pull-right'

app/views/lamination_glue_types/edit.html.slim
section.content-header
  h1
    i.fa.fa-list>
    =t '.title'

section.content
  = render 'form'

app/views/lamination_glue_types/index.html.slim
section.content-header
  h1
    i.fa.fa-list>
    =t '.title'

section.content
  .box
    .box-header.with-border
      = link_to t('.actions.add'), new_lamination_glue_type_path, class: 'btn btn-success'
    .box-body.no-padding
      table.table.table-striped
        thead
          tr
            th=t '.table.name'
            th=t '.table.lamination_type'
            th
        tbody
          - @lamination_glue_types.each do |lamination_glue_type|
            tr id=dom_id(lamination_glue_type)
              td= link_to_if policy(lamination_glue_type).edit?, lamination_glue_type.name, edit_lamination_glue_type_path(lamination_glue_type)
              td= lamination_glue_type.lamination_type.name
              td
                - if policy(lamination_glue_type).destroy?
                  = link_to lamination_glue_type_path(lamination_glue_type), method: :delete, data: { confirm: t('shared.are_you_sure') } do
                    i.fa.fa-trash
    .box-footer
      = paginate @lamination_glue_types, theme: 'twitter-bootstrap-3'

app/views/lamination_glue_types/new.html.slim
section.content-header
  h1
    i.fa.fa-list>
    =t '.title'

section.content
  = render 'form'