config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /en|pl/ do
    devise_for :users, controllers: { sessions: 'customized_devise/sessions' }

    root 'welcome#index'
    resources :users, except: :show
    resources :product_structures, except: :show
    resources :color_presets, except: :show
    resources :clients, except: :show
    resources :templates, except: :show
    resources :backgrounds, except: :show
    resources :machines, except: :show
    resources :clients, except: :show
    resources :machine_parameters, except: :show
    resources :lacquering_aniloxes, except: :show
    resources :lacquering_names, except: :show
    resources :lacquering_polymers, except: :show
    resources :lacquering_types, except: :show
    resources :lacquering_indices, except: :show
    resources :lamination_glues, except: :show
    resources :lamination_machines, except: :show
    resources :lamination_types, except: :show
    resources :lamination_glue_types, except: :show
    resources :lamination_glue_systems, except: :show
    resources :lamination_indices, except: :show
    resources :lamination_roto_glue_names, except: :show
    resources :lamination_roto_glue_types, except: :show
    resources :lamination_roto_linearities, except: :show
    resources :lamination_roto_presers, except: :show
    resources :lamination_roto_indices, except: :show
    resources :cutting_indices, except: :show
    resources :cutting_machines, except: :show
    resources :roto_linearities, except: :show
    resources :roto_paints, except: :show
    resources :roto_presers, except: :show
    resources :roto_indices, except: :show
    resources :paint_providers, except: :show
    resources :paints, except: :show
    resources :acetate_providers, except: :show
    resources :template_background_providers, except: :show
    resources :template_background_prices, except: :show
    resources :offset_plates, except: :show
    resources :offset_plate_providers, except: :show
    resources :azote_providers, except: :show
    resources :pack_providers, except: :show
    resources :orders do
      member do
        get :actualize_edit
        get :pdf_main
        get :pdf_for_print
        get :pdf_after_print
        get :pdf_lamination_1
        get :pdf_lamination_2
        get :price_edit
        patch :actualize_update
        patch :prepared_update
        patch :rollback_update
        patch :start_print_update
        patch :finish_print_update
        patch :start_cut_update
        patch :finish_cut_update
        patch :give_away_update
        patch :update_order_additional_info
        patch :cant_prepare_materials_update
        patch :start_lamination_first_update
        patch :finish_lamination_first_update
        patch :start_lamination_second_update
        patch :finish_lamination_second_update
        patch :price_update
      end
    end
  end
end

app/models/lacquering_name.rb
class LacqueringName < ActiveRecord::Base
  belongs_to :machine
  has_many :orders

  validates :value, presence: true
  validates :machine_id, presence: true
end

app/controllers/lacquering_names_controller.rb
class LacqueringNamesController < ApplicationController
  before_action :set_and_authorize_lacquering_name, only: [:edit, :update, :destroy]

  # GET /lacquering_names
  def index
    authorize LacqueringName
    @lacquering_names = policy_scope(LacqueringName)
    @lacquering_names = @lacquering_names.order(id: :asc)
    @lacquering_names = @lacquering_names.page(params[:page]).per(25)
  end

  # GET /lacquering_names/new
  def new
    authorize LacqueringName
    @lacquering_name = LacqueringName.new
  end

  # POST /lacquering_names
  def create
    authorize LacqueringName
    @lacquering_name = LacqueringName.new(lacquering_name_params)
    if @lacquering_name.save
      redirect_to lacquering_names_url, notice: t('shared.created')
    else
      render :new
    end
  end

  # GET /lacquering_names/:id/edit
  def edit
  end

  # PATCH/PUT /lacquering_names/:id
  def update
    if @lacquering_name.update(lacquering_name_params)
      redirect_to edit_lacquering_name_url(@lacquering_name),
                  notice: t('shared.updated')
    else
      render :edit
    end
  end

  # DELETE /lacquering_names/:id
  def destroy
    if @lacquering_name.destroy
      redirect_to lacquering_names_url, notice: t('shared.destroyed')
    else
      redirect_to lacquering_names_url, alert: t('shared.not_destroyed')
    end
  end

  private

  def lacquering_name_params
    params.require(:lacquering_name).permit(:value, :machine_id)
  end

  def set_and_authorize_lacquering_name
    @lacquering_name = LacqueringName.find(params[:id])
    authorize @lacquering_name
  end
end

app/views/lacquering_names/_form.html.slim
.box.box-primary
  .box-body
    = simple_form_for @lacquering_name, html: { class: 'form-horizontal' } do |f|
      = f.input :machine_id, collection: machines_data_for_select, include_blank: true
      = f.input :value

      .box-footer
        => link_to t('shared.back'), lacquering_names_path, class: 'btn btn-default'
        => f.button :submit, f.object.new_record? ? t('shared.create') : t('shared.save'), class: 'btn btn-primary pull-right'

app/views/lacquering_names/edit.html.slim
section.content-header
  h1
    i.fa.fa-list>
    =t '.title'

section.content
  = render 'form'

app/views/lacquering_names/index.html.slim
section.content-header
  h1
    i.fa.fa-list>
    =t '.title'

section.content
  .box
    .box-header.with-border
      = link_to t('.actions.add'), new_lacquering_name_path, class: 'btn btn-success'
    .box-body.no-padding
      table.table.table-striped
        thead
          tr
            th= t '.table.value'
            th=t '.table.machine'
            th
        tbody
          - @lacquering_names.each do |lacquering_name|
            tr id=dom_id(lacquering_name)
              td= link_to_if policy(lacquering_name).edit?, lacquering_name.value, edit_lacquering_name_path(lacquering_name)
              td= lacquering_name.machine.name
              td
                - if policy(lacquering_name).destroy?
                  = link_to lacquering_name_path(lacquering_name), method: :delete, data: { confirm: t('shared.are_you_sure') } do
                    i.fa.fa-trash
    .box-footer
      = paginate @lacquering_names, theme: 'twitter-bootstrap-3'

app/views/lacquering_names/new.html.slim
section.content-header
  h1
    i.fa.fa-list>
    =t '.title'

section.content
  = render 'form'