config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /en|pl/ do
    devise_for :users, controllers: { sessions: 'customized_devise/sessions' }

    root 'welcome#index'
    resources :users, except: :show
    resources :product_structures, except: :show
    resources :color_presets, except: :show
    resources :clients, except: :show
    resources :templates, except: :show
    resources :backgrounds, except: :show
    resources :machines, except: :show
    resources :clients, except: :show
    resources :machine_parameters, except: :show
    resources :lacquering_aniloxes, except: :show
    resources :lacquering_names, except: :show
    resources :lacquering_polymers, except: :show
    resources :lacquering_types, except: :show
    resources :lacquering_indices, except: :show
    resources :lamination_glues, except: :show
    resources :lamination_machines, except: :show
    resources :lamination_types, except: :show
    resources :lamination_glue_types, except: :show
    resources :lamination_glue_systems, except: :show
    resources :lamination_indices, except: :show
    resources :lamination_roto_glue_names, except: :show
    resources :lamination_roto_glue_types, except: :show
    resources :lamination_roto_linearities, except: :show
    resources :lamination_roto_presers, except: :show
    resources :lamination_roto_indices, except: :show
    resources :cutting_indices, except: :show
    resources :cutting_machines, except: :show
    resources :roto_linearities, except: :show
    resources :roto_paints, except: :show
    resources :roto_presers, except: :show
    resources :roto_indices, except: :show
    resources :paint_providers, except: :show
    resources :paints, except: :show
    resources :acetate_providers, except: :show
    resources :template_background_providers, except: :show
    resources :template_background_prices, except: :show
    resources :offset_plates, except: :show
    resources :offset_plate_providers, except: :show
    resources :azote_providers, except: :show
    resources :pack_providers, except: :show
    resources :orders do
      member do
        get :actualize_edit
        get :pdf_main
        get :pdf_for_print
        get :pdf_after_print
        get :pdf_lamination_1
        get :pdf_lamination_2
        get :price_edit
        patch :actualize_update
        patch :prepared_update
        patch :rollback_update
        patch :start_print_update
        patch :finish_print_update
        patch :start_cut_update
        patch :finish_cut_update
        patch :give_away_update
        patch :update_order_additional_info
        patch :cant_prepare_materials_update
        patch :start_lamination_first_update
        patch :finish_lamination_first_update
        patch :start_lamination_second_update
        patch :finish_lamination_second_update
        patch :price_update
      end
    end
  end
end

app/models/offset_plate_provider.rb
class OffsetPlateProvider < ActiveRecord::Base
  has_many :offset_plate_prices, dependent: :destroy
  has_many :orders, dependent: :restrict_with_error

  accepts_nested_attributes_for :offset_plate_prices,
                                reject_if: :all_blank,
                                allow_destroy: true

  validates :name, presence: true
end

app/controllers/offset_plate_providers_controller.rb
class OffsetPlateProvidersController < ApplicationController
  before_action :set_and_authorize_offset_plate_provider, only: [:edit, :update, :destroy]

  # GET /offset_plate_providers
  def index
    authorize OffsetPlateProvider
    @offset_plate_providers = policy_scope(OffsetPlateProvider)
    @offset_plate_providers = @offset_plate_providers.order(id: :asc)
    @offset_plate_providers = @offset_plate_providers.page(params[:page]).per(25)
  end

  # GET /offset_plate_providers/new
  def new
    authorize OffsetPlateProvider
    @offset_plate_provider = OffsetPlateProvider.new
  end

  # POST /offset_plate_providers
  def create
    authorize OffsetPlateProvider
    @offset_plate_provider = OffsetPlateProvider.new(offset_plate_provider_params)
    if @offset_plate_provider.save
      redirect_to offset_plate_providers_url, notice: t('shared.created')
    else
      render :new
    end
  end

  # GET /offset_plate_providers/:id/edit
  def edit
  end

  # PATCH/PUT /offset_plate_providers/:id
  def update
    if @offset_plate_provider.update(offset_plate_provider_params)
      redirect_to edit_offset_plate_provider_url(@offset_plate_provider),
                  notice: t('shared.updated')
    else
      render :edit
    end
  end

  # DELETE /offset_plate_providers/:id
  def destroy
    if @offset_plate_provider.destroy
      redirect_to offset_plate_providers_url, notice: t('shared.destroyed')
    else
      redirect_to offset_plate_providers_url, alert: t('shared.not_destroyed')
    end
  end

  private

  def offset_plate_provider_params
    params.require(:offset_plate_provider).permit(
      :name,
      offset_plate_prices_attributes: [
        :id, :price, :price_currency,
        :pack_amount, :pack_unit,
        :offset_plate_id, :_destroy
      ]
    )
  end

  def set_and_authorize_offset_plate_provider
    @offset_plate_provider = OffsetPlateProvider.find(params[:id])
    authorize @offset_plate_provider
  end
end

app/views/offset_plate_providers/_form.html.slim
= simple_form_for @offset_plate_provider, html: { class: 'form-horizontal' } do |f|
  .box.box-primary
    .box-body
      = f.input :name

  h4= t('.offset_plate_prices.title')

  #offset_plate_prices
    = f.simple_fields_for :offset_plate_prices do |price|
      = render 'offset_plate_price_fields', f: price

  .box.box-solid
    .box-body
      .links
        = link_to_add_association t('.offset_plate_prices.add'), f, :offset_plate_prices, class: 'btn btn-success', data: { 'association-insertion-node' => '#offset_plate_prices', 'association-insertion-method' => 'append' }

  .box.box-solid
    .box-footer
      => link_to t('shared.back'), offset_plate_providers_path, class: 'btn btn-default'
      => f.button :submit, f.object.new_record? ? t('shared.create') : t('shared.save'), class: 'btn btn-primary pull-right'

app/views/offset_plate_providers/_offset_plate_price_fields.html.slim
.box
  .box-body
    .nested-fields
      = f.input :offset_plate_id, collection: OffsetPlate.all.map{ |p| ["#{p.name} (#{p.cylinder.name})", p.id] }, include_blank: true
      = f.input :price
      = f.input :price_currency, collection: currency_for_select, include_blank: false
      = f.input :pack_amount
      = f.input :pack_unit, collection: units_for_select, include_blank: true
      .text-right
        = link_to_remove_association t('.delete'), f, class: 'btn btn-danger'

app/views/offset_plate_providers/edit.html.slim
section.content-header
  h1
    i.fa.fa-list>
    =t '.title'

section.content
  = render 'form'

app/views/offset_plate_providers/index.html.slim
section.content-header
  h1
    i.fa.fa-list>
    =t '.title'

section.content
  .box
    .box-header.with-border
      = link_to t('.actions.add'), new_offset_plate_provider_path, class: 'btn btn-success'
    .box-body.no-padding
      table.table.table-striped
        thead
          tr
            th=t '.table.name'
            th
        tbody
          - @offset_plate_providers.each do |offset_plate_provider|
            tr id=dom_id(offset_plate_provider)
              td= link_to_if policy(offset_plate_provider).edit?, offset_plate_provider.name, edit_offset_plate_provider_path(offset_plate_provider)
              td
                - if policy(offset_plate_provider).destroy?
                  = link_to offset_plate_provider_path(offset_plate_provider), method: :delete, data: { confirm: t('shared.are_you_sure') } do
                    i.fa.fa-trash
    .box-footer
      = paginate @offset_plate_providers, theme: 'twitter-bootstrap-3'

app/views/offset_plate_providers/new.html.slim
section.content-header
  h1
    i.fa.fa-list>
    =t '.title'

section.content
  = render 'form'