config/routes.rb
Rails.application.routes.draw do

  scope '(:locale)', locale: /en|pl/ do
    devise_for :users, controllers: { sessions: 'customized_devise/sessions' }

    root 'welcome#index'
    resources :users, except: :show
    resources :product_structures, except: :show
    resources :color_presets, except: :show
    resources :clients, except: :show
    resources :templates, except: :show
    resources :backgrounds, except: :show
    resources :machines, except: :show
    resources :clients, except: :show
    resources :machine_parameters, except: :show
    resources :lacquering_aniloxes, except: :show
    resources :lacquering_names, except: :show
    resources :lacquering_polymers, except: :show
    resources :lacquering_types, except: :show
    resources :lacquering_indices, except: :show
    resources :lamination_glues, except: :show
    resources :lamination_machines, except: :show
    resources :lamination_types, except: :show
    resources :lamination_glue_types, except: :show
    resources :lamination_glue_systems, except: :show
    resources :lamination_indices, except: :show
    resources :lamination_roto_glue_names, except: :show
    resources :lamination_roto_glue_types, except: :show
    resources :lamination_roto_linearities, except: :show
    resources :lamination_roto_presers, except: :show
    resources :lamination_roto_indices, except: :show
    resources :cutting_indices, except: :show
    resources :cutting_machines, except: :show
    resources :roto_linearities, except: :show
    resources :roto_paints, except: :show
    resources :roto_presers, except: :show
    resources :roto_indices, except: :show
    resources :paint_providers, except: :show
    resources :paints, except: :show
    resources :acetate_providers, except: :show
    resources :template_background_providers, except: :show
    resources :template_background_prices, except: :show
    resources :offset_plates, except: :show
    resources :offset_plate_providers, except: :show
    resources :azote_providers, except: :show
    resources :pack_providers, except: :show
    resources :orders do
      member do
        get :actualize_edit
        get :pdf_main
        get :pdf_for_print
        get :pdf_after_print
        get :pdf_lamination_1
        get :pdf_lamination_2
        get :price_edit
        patch :actualize_update
        patch :prepared_update
        patch :rollback_update
        patch :start_print_update
        patch :finish_print_update
        patch :start_cut_update
        patch :finish_cut_update
        patch :give_away_update
        patch :update_order_additional_info
        patch :cant_prepare_materials_update
        patch :start_lamination_first_update
        patch :finish_lamination_first_update
        patch :start_lamination_second_update
        patch :finish_lamination_second_update
        patch :price_update
      end
    end
  end
end

app/models/pack_provider.rb
class PackProvider < ActiveRecord::Base
  has_many :orders, dependent: :restrict_with_error

  validates :name, presence: true
end

app/controllers/pack_providers_controller.rb
class PackProvidersController < ApplicationController
  before_action :set_and_authorize_pack_provider, only: [:edit, :update, :destroy]

  # GET /pack_providers
  def index
    authorize PackProvider
    @pack_providers = policy_scope(PackProvider)
    @pack_providers = @pack_providers.order(id: :asc)
    @pack_providers = @pack_providers.page(params[:page]).per(25)
  end

  # GET /pack_providers/new
  def new
    authorize PackProvider
    @pack_provider = PackProvider.new
  end

  # POST /pack_providers
  def create
    authorize PackProvider
    @pack_provider = PackProvider.new(pack_provider_params)
    if @pack_provider.save
      redirect_to pack_providers_url, notice: t('shared.created')
    else
      render :new
    end
  end

  # GET /pack_providers/:id/edit
  def edit
  end

  # PATCH/PUT /pack_providers/:id
  def update
    if @pack_provider.update(pack_provider_params)
      redirect_to edit_pack_provider_url(@pack_provider), notice: t('shared.updated')
    else
      render :edit
    end
  end

  # DELETE /pack_providers/:id
  def destroy
    if @pack_provider.destroy
      redirect_to pack_providers_url, notice: t('shared.destroyed')
    else
      redirect_to pack_providers_url, alert: t('shared.not_destroyed')
    end
  end

  private

  def pack_provider_params
    params.require(:pack_provider).permit(:name)
  end

  def set_and_authorize_pack_provider
    @pack_provider = PackProvider.find(params[:id])
    authorize @pack_provider
  end
end

app/views/pack_providers/_form.html.slim
.box.box-primary
  .box-body
    = simple_form_for @pack_provider, html: { class: 'form-horizontal' } do |f|
      = f.input :name

      .box-footer
        => link_to t('shared.back'), pack_providers_path, class: 'btn btn-default'
        => f.button :submit, f.object.new_record? ? t('shared.create') : t('shared.save'), class: 'btn btn-primary pull-right'

app/views/pack_providers/edit.html.slim
section.content-header
  h1
    i.fa.fa-list>
    =t '.title'

section.content
  = render 'form'

app/views/pack_providers/index.html.slim
section.content-header
  h1
    i.fa.fa-list>
    =t '.title'

section.content
  .box
    .box-header.with-border
      = link_to t('.actions.add'), new_pack_provider_path, class: 'btn btn-success'
    .box-body.no-padding
      table.table.table-striped
        thead
          tr
            th=t '.table.name'
            th
        tbody
          - @pack_providers.each do |pack_provider|
            tr id=dom_id(pack_provider)
              td= link_to_if policy(pack_provider).edit?, pack_provider.name, edit_pack_provider_path(pack_provider)
              td
                - if policy(pack_provider).destroy?
                  = link_to pack_provider_path(pack_provider), method: :delete, data: { confirm: t('shared.are_you_sure') } do
                    i.fa.fa-trash
    .box-footer
      = paginate @pack_providers, theme: 'twitter-bootstrap-3'

app/views/pack_providers/new.html.slim
section.content-header
  h1
    i.fa.fa-list>
    =t '.title'

section.content
  = render 'form'